import esbuild from 'esbuild';
import manifest from './manifest.json' assert { type: 'json' };
import { sassPlugin } from 'esbuild-sass-plugin';

const banner = `/*
-------------------------------------------
${manifest.name} - Release Build
-------------------------------------------
By: ${manifest.author} (${manifest.authorUrl})
Time: ${new Date().toUTCString()}
Version: ${manifest.version}
-------------------------------------------
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this theme
*/
`;

const build = await esbuild.build({
	banner: {
		css: banner,
	},
	entryPoints: ['src/index.scss'],
	logLevel: 'info',
	outfile: 'theme.css',
	plugins: [
		sassPlugin({
			cache: true,
			charset: false,
			alertColor: true,
			alertAscii: true,
		}),
	],
});
